// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1lR8AnpuIBqj12lYUGRoRgkfWGLAbupo',
    appId: '1:843695315972:web:feec4360f7f1b659e92951',
    messagingSenderId: '843695315972',
    projectId: 'prueba2-flutter-45456',
    authDomain: 'prueba2-flutter-45456.firebaseapp.com',
    databaseURL: 'https://prueba2-flutter-45456-default-rtdb.firebaseio.com',
    storageBucket: 'prueba2-flutter-45456.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMJ-Ma7_RuRWjN7TQNWZet9_yYJ-Az1Po',
    appId: '1:843695315972:android:fe89cfb7ef0cffbce92951',
    messagingSenderId: '843695315972',
    projectId: 'prueba2-flutter-45456',
    databaseURL: 'https://prueba2-flutter-45456-default-rtdb.firebaseio.com',
    storageBucket: 'prueba2-flutter-45456.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1lR8AnpuIBqj12lYUGRoRgkfWGLAbupo',
    appId: '1:843695315972:web:666c00aa1f951181e92951',
    messagingSenderId: '843695315972',
    projectId: 'prueba2-flutter-45456',
    authDomain: 'prueba2-flutter-45456.firebaseapp.com',
    databaseURL: 'https://prueba2-flutter-45456-default-rtdb.firebaseio.com',
    storageBucket: 'prueba2-flutter-45456.firebasestorage.app',
  );

}